name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/new-endpoint

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Lint code
        run: flake8 hello-devops/

  test-job:
    runs-on: ubuntu-latest
    needs: lint-job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r hello-devops/requirements.txt
      - name: Run tests
        run: python -m pytest hello-devops/
      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging
        run: echo "Déploiement en staging..."
        
  validate:
    runs-on: ubuntu-latest
    needs: deploy-job
    steps:
      - name: Vérification de l'application déployée
        run: |
          curl http://localhost:5000 && echo "L'application est opérationnelle!"
