name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Assurez-vous que vous poussez sur la branche master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r ../requirements.txt  # Utilisation du chemin relatif correct

    - name: Run Tests
      run: python -m unittest discover -s hello-devops  # Test dans hello-devops/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy App
      run: echo "Deploying application..."
